FROM python:3
ENV PYTHONUNBUFFERED 1

RUN mkdir /code
WORKDIR /code

RUN pip install uwsgi

COPY requirements.txt /code/
RUN pip install -r requirements.txt

COPY . /code/

RUN python manage.py collectstatic

EXPOSE 8080
CMD ["uwsgi", "--ini", "/code/cic-dashboard.ini"]