FROM python:3
ENV PYTHONUNBUFFERED 1
ENV ENVIRONMENT DEV
ENV SECRET_KEY 1$qpv*d%uoex8xe!as6r0#3s@kz1)e&tpb5a@@@)y#dr(5_**t

RUN mkdir /code
RUN mkdir /code/static

WORKDIR /code

RUN pip install uwsgi

COPY requirements.txt /code/
RUN pip install -r requirements.txt

# COPY ./entrypoint.sh /code/entrypoint.sh

COPY . /code/

RUN python3 manage.py collectstatic

EXPOSE 8080

CMD ["uwsgi", "--ini", "/code/cic-dashboard.ini"]

#CMD ["python", "manage.py", "runserver", "8080"]