# Generated by Django 3.0.3 on 2020-03-21 18:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CicReportingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('s_gender', models.CharField(blank=True, max_length=50, null=True)),
                ('s_business_type', models.CharField(blank=True, max_length=255, null=True)),
                ('s_location', models.TextField(blank=True, null=True)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('t_gender', models.CharField(blank=True, max_length=50, null=True)),
                ('t_business_type', models.CharField(blank=True, max_length=255, null=True)),
                ('t_location', models.TextField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('tokenname', models.CharField(blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('transfer_subtype', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_use', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('row_created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'cic_reporting_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CicUsers',
            fields=[
                ('postgres_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('roles', django.contrib.postgres.fields.jsonb.JSONField()),
                ('current_blockchain_address', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('previous_blockchain_address', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, max_length=255, null=True)),
                ('bal', models.FloatField(blank=True, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('last_send', models.DateTimeField(blank=True, null=True)),
                ('delete_flag', models.BooleanField()),
                ('row_created_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'cic_users',
                'managed': False,
            },
        ),
    ]
